### ISSUE TITLE
Add Apple CDN Debug Headers to AASA checks

### ISSUE THREAD

**Issue by chayev** [chayev/yurl#68]
Since iOS 14, Apple now caches the AASA file from the properties domain and uses the cache when the app is installed. 

Checking against https://app-site-association.cdn-apple.com/a/v1/[DOMAIN] returning headers that are useful to debug.

Add support for this to both the CLI and web app. Note: update the file in yurllib should automatically add support for both as long as the new functionality is wrapped by the main function (CheckAASADomain).

**Comment by aceslick911** [comment]
Hi @chayev let me know if you need any other help getting this to production 👍 

One additional change I'd recommend making would be throw an error code in the CLI when the deeplinking is presumed to be `not working` due to a failure condition.

This would mean teams could potentially use yurl in CI or automation to detect when problems with deeplinking happen.

Important notes:
- should not throw error code if CDN AASA is out of date - this would cause CI to not be very useful
- we should add code to validate the AASA against spec 
- we could add code to validate url PATHS against the AASA defined paths and/or appid

created new issue: https://github.com/chayev/yurl/issues/69

**Comment by aceslick911** [comment]
in regards to usage in CI
- I'd suggest adding a reCaptcha to the public website, this will steer people away from using it in CI (you're gonna get a massive bill when 1000s of devs flood it) and instead use the CLI directly as part of their build steps which would not require you to pay for the bandwidth 👍

**Comment by chayev** [comment]
Thank you for the feedback and opening the issue @aceslick911. I'll open [another issue](https://github.com/chayev/yurl/issues/70) for the reCaptcha comment, that's not a bad idea. Feel free to work on this if you have time.

I'm running through a few tests currently, once those pass I will make a minor release. 

The error codes suggestion is actually something that has been on my mind. Agreed it would help with those that want to use this during their CI process. Feel free to work on this as well.

**Comment by chayev** [comment]
@aceslick911 these changes were included in the latest release of yURL v0.7.1
